LABELS=["SIZE_TOO_SMALL","SIZE_TOO_LARGE","SIZE_CHART_MISMATCH","LISTING_CONTENT_ERROR","PRODUCT_SPEC_ERROR","CUSTOMER_ORDER_SELECTION","QUALITY_DAMAGE","UNKNOWN_REVIEW"]
CONFIDENCE_THRESHOLD=0.62
HIGH_PRIORITY_THRESHOLD=0.78
MIN_EVIDENCE_HIGH_PRIORITY=2
WORKER_TASK_CAP=25
